language: node_js
node_js:
- "9"
- "10"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
    - zetxx@belogradchik.biz
    on_success: change
    on_failure: always