language: node_js
node_js:
- "9"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: test
      only:
        - master
      script: npm run unit-test
    - stage: release
      only:
        - master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release