language: node_js
node_js:
- "9"
- "10"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release