language: node_js
node_js:
- "9"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: test
      script: npm run unit-test
    #- stage: prerelease
    #  script: npm run semantic-release
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        email: zetxx@belogradchik.biz
        api_key: $NPM_API_KEY
        on: master